title: Profiles
description: |
  Profiles and Q&As with data journalists, ranging from what they do to how they got where they are.
sortorder: 22
items:


  - title: "Ben Casselman: In Data Journalism, Tech Matters Less Than the People"
    url: https://www.nytimes.com/2019/11/13/technology/personaltech/data-journalism-economics.html

    description: |
      Ben Casselman, an economics reporter, uses a programming language called R and works with vast data sets. But he says interviews still make for the best stories.


    summary: |
      In this "Tech We're Using" NYT Q&A, economics reporter Ben Casselman describes using R to work with data too big for Excel and to automate the analysis of monthly reports. But Casselman contends that still he gets his best stories and insights the old-fashioned way.

    images:
      thumbnail:
        path: /static/images/items/ben-casselman-qna.jpg

    publishmeta:
      date: 2019-11-13
      publisher:
        name: New York Times
        url: https://nytimes.com
      authors:
        - name: Ben Casselman
          url: https://www.nytimes.com/by/ben-casselman


    excerpt: |
      Really, though, the most important piece of technology on my desk is my landline telephone. I think some people have the idea that “data journalism” means staring at spreadsheets until a story magically appears, but in the real world that almost never happens. The best stories almost always emerge from talking to people, whether they are experts or just ordinary people affected by the issues we write about. They’re the ones who pose the questions that data can help answer, or who help explain the trends that the data reveals, or who can provide the wrinkles and nuances that the data glosses over.





  - title: "From English To Tech, Sara Simon ’13 Shows What An Open Mind Can Do"
    url: https://thewellesleynews.com/2019/02/28/from-english-to-tech-sara-simon-13-shows-what-an-open-mind-can-do/

    summary: |
      Sara Simon, then with the NYT's interactive news team, describes her path from 7-month coding academy to web developer for public news, to building tools for research and news gathering at the Times.

    excerpt: |
      Even now, working at the New York Times, Simon is aware that a job is just a job — even if it is a great one. She did not decide in college that it was her goal to work at a world-renowned paper. She did not know that she would make a connection between her English degree and technology. By not putting too much pressure on herself to do any one thing, Simon has been able to pursue her interests as they come.

      Her advice to current students? “Definitely keep an open mind, know that your background has prepared you to do well, and trust your gut.”

    images:
      thumbnail:
        path: /static/images/items/thumbnails/sara-simon-alumni-profile.jpg

    publishmeta:
      date: 2019-02-28
      publisher:
        name: The Wellesley News
        url: https://thewellesleynews.com/
      authors:
        - name: Grace Ramsdell
          url: https://thewellesleynews.com/byline/grace-ramsdell/





  - title: "Q&A: Quartz’s David Yanofsky on coding as a journalist"
    url: https://www.cjr.org/tow_center/quartz-david-yanofsky.php

    description: |
      david yanofsky tktktk

    # summary: |
    #   MANUAL_DESCRIPTION

    publishmeta:
      date: 2017-05-22
      publisher:
        name: Columbia Journalism Review
        url: https://www.cjr.org/
      authors:
        - name: Jon Keegan
          url: https://www.cjr.org/author/jkeegan



  - title: "Q&A: ProPublica’s Lena Groeger on data visualization and writing about design"
    url: https://www.cjr.org/tow_center/propublica-lena-groeger-data-visualization-design.php

    description: |
      lena groeger tktk

    # summary: |
    #   MANUAL_DESCRIPTION

    publishmeta:
      date: 2017-07-20
      publisher:
        name: Columbia Journalism Review
        url: https://www.cjr.org/
      authors:
        - name: Jon Keegan
          url: https://www.cjr.org/author/jkeegan

